### ISSUE TITLE
Chakma base letter doesn’t ligate with more than one post-base glyph

### ISSUE THREAD

**Issue by dscorbett** [notofonts/chakma#3]
### Font
NotoSansChakma-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/45d2985250da65f57c3f6df64fd8aec57592a3b5/unhinted/NotoSansChakma/NotoSansChakma-Regular.ttf
Date: 2019-12-29

### Font version
Version 2.001

### Issue
When a post-base <i>yyā</i> is ligated with a post-base vowel sign, the base letter does not ligate with the <i>yyā</i> or the vowel sign, even if it would ligate with one if the other were not present. For example, <i>jhā</i> ligates with post-base <i>ei</i> or <i>yyā</i> but not both together.

### Character data
𑄏𑅆𑄏𑄳𑄠𑄏𑄳𑄠𑅆
U+1110F CHAKMA LETTER JHAA
U+11146 CHAKMA VOWEL SIGN EI
U+1110F CHAKMA LETTER JHAA
U+11133 CHAKMA VIRAMA
U+11120 CHAKMA LETTER YYAA
U+1110F CHAKMA LETTER JHAA
U+11133 CHAKMA VIRAMA
U+11120 CHAKMA LETTER YYAA
U+11146 CHAKMA VOWEL SIGN EI

### Screenshot
![𑄏𑅆𑄏𑄳𑄠𑄏𑄳𑄠𑅆](https://user-images.githubusercontent.com/1124347/71590890-276e0880-2af8-11ea-99cc-e9a67b32cbea.png)

**Comment by SKing-2003** [comment]
This seems to be fixed, so I'm closing it.
